### ISSUE TITLE
POSIX on single-shared-file write tests

### ISSUE THREAD

**Issue by ecamiloinacio** [LLNL/ior#30]
When running a single-shared-file write test using at least two tasks, running on different nodes, using the POSIX api, IOR fails with the following error:

ior ERROR: write() failed, errno 22, Invalid argument (aiori-POSIX.c:236)
application called MPI_Abort(MPI_COMM_WORLD, -1) - process 1

Tests were conducted with IOR 3.0.1 and 2.10.3, using MPICH 3.2 and OrangeFS 2.9.3 as the backend file system. All compute and storage nodes run a CentOS 6.7 Linux, with kernel 2.6.32-573.22.1.el6.x86_64.

The parameters to reproduce the problem are:
mpiexec -n 2 -f mpihosts ior -wvvvv -t 1m -o /mnt/orangefs/testfile

**Comment by roblatham00** [comment]
write failed with invalid argument...  this smells like an OrangeFS bug.  Do other benchmarks to /mnt/oragnefs/testfile work?

**Comment by ecamiloinacio** [comment]
The same problem occurs when running OrangeFS I/O test (included in OrangeFS source files - POSIX/io.c).
An error is logged in the /var/log/messages file in the client node:
src/kernel/linux-2.6/pvfs2-utils.c Critical error: Invalid handle despite using iget4/iget5.

**Comment by roblatham00** [comment]
So, clearly some kind of issue with the orangefs kernel driver.  Did you
build your mpi implementation with pvfs support?  When you report this bug
to the orangefs folks, knowing the state of the mpi-io interface will be
helpful.

**Comment by ecamiloinacio** [comment]
When using MPICH 3.2, I included the options for supporting ROMIO and PVFS2:
./configure --prefix=/opt/mpich-3.1.4 --enable-romio --enable-shared --with-pvfs2=/opt/orangefs --with-file-system=pvfs2

With MPICH 1.5, I had to remove the pvfs2 options because hydra did not compile with them.

**Comment by ecamiloinacio** [comment]
The issue is not observed with OrangeFS 2.8.8, MPICH 3.2 and IOR 3.0.1.
